import React, { Component } from "react";

export default class Content extends Component {
  render() {
    return(
      <div className='content'>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur et mollis tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas purus purus, varius eget tellus sit amet, suscipit auctor lacus. Maecenas semper, nisi sed tristique commodo, metus ex interdum nibh, sit amet aliquam massa sem eu nulla. Maecenas feugiat fermentum dolor eu vehicula. Vestibulum viverra id neque at convallis. Mauris lectus magna, suscipit sagittis aliquet at, iaculis sit amet felis. Mauris porta efficitur nisl, quis vestibulum tellus consequat sit amet. Nullam quis pellentesque elit, ac posuere velit. Phasellus orci purus, suscipit eget erat sit amet, facilisis mattis ipsum. Nam ut est non lectus porta viverra. Ut dapibus faucibus arcu, sit amet aliquet ligula iaculis sit amet. Duis pellentesque lorem eu enim sodales imperdiet. Phasellus egestas lorem leo, eget ullamcorper ex vehicula nec. Duis porttitor aliquam finibus. Sed enim metus, dignissim quis posuere vitae, consequat vel nulla.

Nunc tincidunt, orci ut accumsan aliquam, mauris mauris volutpat mauris, sit amet malesuada arcu ex at nisl. Sed laoreet scelerisque dui nec dictum. Suspendisse ac luctus erat. Vestibulum lobortis leo id cursus eleifend. Nunc quis quam dapibus, scelerisque augue scelerisque, imperdiet quam. Donec eget auctor nunc, at maximus lorem. Nullam porttitor urna nec magna consectetur aliquam. Ut varius erat et risus scelerisque, vitae ultricies elit consectetur. Cras ut semper purus. Donec at hendrerit lorem. Suspendisse interdum velit tristique rutrum iaculis. In sagittis id metus in pretium. Suspendisse rutrum nunc nulla, non venenatis erat volutpat luctus. Vivamus a rutrum ligula. Aliquam quis enim magna. Aenean auctor nunc eget varius pellentesque.

Integer et tortor lectus. Quisque consequat est ut ligula bibendum commodo. Nulla facilisi. Nullam suscipit, erat eu tempor gravida, arcu ipsum bibendum est, eu tincidunt elit turpis non lorem. Proin consectetur mauris massa, sit amet vulputate nibh laoreet ac. Curabitur faucibus, velit quis consequat dictum, magna elit vulputate ipsum, quis egestas odio risus nec dui. Phasellus vitae risus maximus, accumsan elit sed, euismod magna. Integer dapibus risus et velit sollicitudin, rutrum rutrum orci posuere.

Integer vitae auctor elit. Quisque fermentum non lectus eget ultricies. Aliquam congue metus sagittis pellentesque dignissim. Donec eu ex et erat sollicitudin dignissim vitae sodales sem. Etiam quis fringilla nisl. Pellentesque a varius nisl, ut semper elit. Quisque nulla tortor, tristique iaculis turpis sed, lobortis suscipit lorem. Proin vel sapien id risus volutpat vestibulum. Etiam tempus sed turpis id mollis. Morbi et nulla tortor. Donec vel purus diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

In aliquet suscipit neque ac laoreet. Aenean molestie, quam a imperdiet dictum, nisi quam porttitor urna, eget sagittis risus felis eu erat. Duis fringilla nulla quam, eget sollicitudin est ornare eu. Morbi at mattis nulla, in scelerisque risus. Nunc in sollicitudin arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec rhoncus, nisl commodo convallis accumsan, neque augue auctor nunc, sed posuere sem mi at lectus. Sed molestie, urna et finibus maximus, risus lorem volutpat justo, viverra dictum lorem nunc id risus. Fusce vestibulum ante eu dui rhoncus, et volutpat justo ornare.
      </div>
    )
  }
}